[package]
name = "kyoyu"
version = "0.1.0"
authors = ["amy null <null@amy.gg>"]
edition = "2018"

[dependencies]
scrap = { git = "https://github.com/queer/scrap.git", rev = "1ab2fdffbc9375e923797a3b2a8319b90f0e6ab4" }
png = "0.16.8"
image = "0.23.14"
druid = "0.7.0"
